name: Generic checks for commits and pull requests

on:
  push:
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'

jobs:
  # Pylint
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r server/requirements-dev.txt

      - name: Run Pylint
        run: pylint --output-format=github app
        working-directory: ./server

  # Pyright
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r server/requirements-dev.txt

      - name: Run Pyright
        run: pyright app
        working-directory: ./server

  # Bandit
  securitycheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r server/requirements-dev.txt

      - name: Run Bandit
        run: bandit -c pyproject.toml -r app
        working-directory: ./server

  # deptry
  dep-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r server/requirements-dev.txt

      - name: Run deptry
        run: deptry -go .
        working-directory: ./server

  # Pytest
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r server/requirements-dev.txt

      - name: Run Pytest
        run: pytest .
        working-directory: ./server
