name: Generic checks for commits and pull requests

on:
  push:
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'

jobs:
  # Pylint
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -e server[dev]

      - name: Run Pylint
        run: pylint --output-format=github server/app/

  # Pyright
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -e server[dev]

      - name: Run Pyright
        run: pyright server/app/

  # Bandit
  securitycheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -e server[dev]

      - name: Run Bandit
        run: bandit -r server/app/

  # Pytest
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -e server[dev]

      - name: Run Pytest
        run: pytest server
