name: Dependency vulnerability scanning

on:
  schedule:
    - cron: "0 0,6,12 * * *"
  push:
    paths:
      - 'server/pyproject.toml'
  pull_request:
    paths:
      - 'server/pyproject.toml'

jobs:
    pyscan:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v7
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: pip install -e server[dev]

        - name: Run pyscan
          run: pyscan -d server
